package normalize

import (
	"bufio"
	"os"
	"testing"
)

func readLines(t testing.TB, path string) []string {
	t.Helper()
	f, err := os.Open(path)
	if err != nil {
		t.Fatalf("open %s: %v", path, err)
	}
	defer f.Close()
	var lines []string
	sc := bufio.NewScanner(f)
	sc.Buffer(make([]byte, 0, 1<<20), 1<<24)
	for sc.Scan() {
		lines = append(lines, sc.Text())
	}
	if err := sc.Err(); err != nil {
		t.Fatalf("read %s: %v", path, err)
	}
	return lines
}

// TestGolden checks Normalize matches PyThaiNLP's normalize() byte-for-byte over
// a set of edge cases (testdata/norm.txt → norm.golden, generated by PyThaiNLP).
func TestGolden(t *testing.T) {
	in := readLines(t, "testdata/norm.txt")
	gold := readLines(t, "testdata/norm.golden")
	if len(in) != len(gold) {
		t.Fatalf("line count mismatch: in=%d gold=%d", len(in), len(gold))
	}
	diffs := 0
	for i := range in {
		if got := Normalize(in[i]); got != gold[i] {
			diffs++
			t.Errorf("line %d\n  in  =%q\n  got =%q\n  want=%q", i+1, in[i], got, gold[i])
		}
	}
	if diffs == 0 {
		t.Logf("✅ %d lines match PyThaiNLP normalize() exactly", len(in))
	}
}

// TestNewlines covers multi-line inputs (which the line-based golden file can't
// hold). Expected values were produced by PyThaiNLP normalize().
func TestNewlines(t *testing.T) {
	cases := []struct{ in, want string }{
		{"ก\nข", "ก\nข"},
		{"ก \n ข", "ก\nข"},
		{"ก\n\nข", "ก\nข"},
		{"ก \n\n ค", "ก\nค"},
		{"บรรทัด1\nบรรทัด2", "บรรทัด1\nบรรทัด2"},
		{"ก\n  \nข", "ก\nข"},
	}
	for _, c := range cases {
		if got := Normalize(c.in); got != c.want {
			t.Errorf("Normalize(%q) = %q, want %q", c.in, got, c.want)
		}
	}
}

// TestDeterministic checks repeated calls on the same input give the same output.
func TestDeterministic(t *testing.T) {
	for _, s := range readLines(t, "testdata/norm.txt") {
		if a, b := Normalize(s), Normalize(s); a != b {
			t.Errorf("non-deterministic for %q: %q vs %q", s, a, b)
		}
	}
}

func TestEmpty(t *testing.T) {
	if got := Normalize(""); got != "" {
		t.Errorf("Normalize(\"\") = %q, want \"\"", got)
	}
}
