//go:build ignore

// genreport runs the test suite and benchmarks and writes docs/TEST-REPORT.md,
// a snapshot (with git commit + date) used to track quality and performance
// across versions. Run via `make report` or `go run scripts/genreport.go`.
package main

import (
	"bufio"
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"regexp"
	"sort"
	"strings"
	"time"
)

type event struct {
	Action  string
	Package string
	Test    string
	Elapsed float64
	Output  string
}

type testResult struct {
	pkg, name, action string
	elapsed           float64
}

func main() {
	tests, coverage := runTests()
	benches := runBenches()

	var b strings.Builder
	fmt.Fprintf(&b, "# Test & Benchmark Report\n\n")
	fmt.Fprintf(&b, "_Generated: %s | commit: %s | %s_\n\n",
		time.Now().UTC().Format("2006-01-02 15:04 UTC"), gitCommit(), goVersion())
	fmt.Fprintf(&b, "> Auto-generated by `make report`. Regenerate to track changes over time.\n\n")

	// summary
	pass, fail, skip := 0, 0, 0
	for _, t := range tests {
		switch t.action {
		case "pass":
			pass++
		case "fail":
			fail++
		case "skip":
			skip++
		}
	}
	status := "✅ all passing"
	if fail > 0 {
		status = fmt.Sprintf("❌ %d failing", fail)
	}
	fmt.Fprintf(&b, "## Summary\n\n")
	fmt.Fprintf(&b, "- **Status:** %s\n", status)
	fmt.Fprintf(&b, "- **Tests:** %d passed, %d failed, %d skipped\n", pass, fail, skip)
	fmt.Fprintf(&b, "- **Benchmarks:** %d\n\n", len(benches))

	// coverage
	fmt.Fprintf(&b, "## Coverage\n\n| Package | Coverage |\n| --- | --- |\n")
	pkgs := make([]string, 0, len(coverage))
	for p := range coverage {
		pkgs = append(pkgs, p)
	}
	sort.Strings(pkgs)
	for _, p := range pkgs {
		fmt.Fprintf(&b, "| `%s` | %s |\n", short(p), coverage[p])
	}
	fmt.Fprintf(&b, "\n")

	// test cases
	fmt.Fprintf(&b, "## Test cases\n\n| Result | Package | Test | Time |\n| --- | --- | --- | --- |\n")
	sort.Slice(tests, func(i, j int) bool {
		if tests[i].pkg != tests[j].pkg {
			return tests[i].pkg < tests[j].pkg
		}
		return tests[i].name < tests[j].name
	})
	for _, t := range tests {
		if t.name == "" {
			continue
		}
		icon := map[string]string{"pass": "✅", "fail": "❌", "skip": "⏭️"}[t.action]
		fmt.Fprintf(&b, "| %s | `%s` | %s | %.2fs |\n", icon, short(t.pkg), t.name, t.elapsed)
	}
	fmt.Fprintf(&b, "\n")

	// benchmarks
	fmt.Fprintf(&b, "## Benchmarks\n\n```\n")
	for _, line := range benches {
		fmt.Fprintf(&b, "%s\n", line)
	}
	fmt.Fprintf(&b, "```\n")

	if err := os.MkdirAll("docs", 0o755); err != nil {
		fatal(err)
	}
	if err := os.WriteFile("docs/TEST-REPORT.md", []byte(b.String()), 0o644); err != nil {
		fatal(err)
	}
	fmt.Printf("wrote docs/TEST-REPORT.md — %d tests (%d pass, %d fail), %d benchmarks\n",
		len(tests), pass, fail, len(benches))
	if fail > 0 {
		os.Exit(1)
	}
}

func runTests() ([]testResult, map[string]string) {
	cmd := exec.Command("go", "test", "-json", "-cover", "./...")
	out, _ := cmd.Output() // ignore exit code; failures are in the JSON
	var results []testResult
	coverage := map[string]string{}
	covRe := regexp.MustCompile(`coverage: ([\d.]+%) of statements`)
	noTest := regexp.MustCompile(`\[no test files\]`)
	sc := bufio.NewScanner(bytes.NewReader(out))
	sc.Buffer(make([]byte, 0, 1<<20), 1<<24)
	for sc.Scan() {
		var e event
		if json.Unmarshal(sc.Bytes(), &e) != nil {
			continue
		}
		if e.Test != "" && (e.Action == "pass" || e.Action == "fail" || e.Action == "skip") {
			results = append(results, testResult{e.Package, e.Test, e.Action, e.Elapsed})
		}
		if e.Test == "" && e.Action == "output" {
			if m := covRe.FindStringSubmatch(e.Output); m != nil {
				coverage[e.Package] = m[1]
			} else if noTest.MatchString(e.Output) {
				if _, ok := coverage[e.Package]; !ok {
					coverage[e.Package] = "—"
				}
			}
		}
	}
	return results, coverage
}

func runBenches() []string {
	cmd := exec.Command("go", "test", "-run=^$", "-bench=.", "-benchmem", "./...")
	out, _ := cmd.Output()
	var lines []string
	sc := bufio.NewScanner(bytes.NewReader(out))
	for sc.Scan() {
		if strings.HasPrefix(sc.Text(), "Benchmark") {
			lines = append(lines, strings.Join(strings.Fields(sc.Text()), "  "))
		}
	}
	return lines
}

func gitCommit() string {
	out, err := exec.Command("git", "rev-parse", "--short", "HEAD").Output()
	if err != nil {
		return "unknown"
	}
	return strings.TrimSpace(string(out))
}

func goVersion() string {
	out, _ := exec.Command("go", "version").Output()
	f := strings.Fields(string(out))
	if len(f) >= 3 {
		return f[2]
	}
	return "go"
}

func short(pkg string) string {
	const prefix = "github.com/sukitss/thai-nlp-go"
	if pkg == prefix {
		return "."
	}
	return strings.TrimPrefix(pkg, prefix+"/")
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, "genreport:", err)
	os.Exit(1)
}
